{{--
    Aset PWA: web app manifest, ikon, theme-color, dan apple-touch-startup-image.

    Android TIDAK memakai startup image. Chrome membuat splash sendiri dari
    icon + background_color di manifest. Yang perlu file manual hanya iOS,
    satu link per resolusi perangkat.

    Generated by `php artisan pwa:assets`. Kalau file gambarnya hilang atau
    404, blok ini tetap aman - browser hanya mengabaikan link yang gagal.
--}}

{{-- Web app manifest --}}
<link rel="manifest" href="{{ asset('manifest.webmanifest') }}">

{{-- Ikon. favicon.ico bawaan tidak dipakai karena 0 byte --}}
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('pwa/favicon-32.png') }}">
<link rel="icon" type="image/png" sizes="192x192" href="{{ asset('pwa/icon-192.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('pwa/apple-touch-icon.png') }}">

{{-- Warna UI browser. Dua varian supaya address bar ikut mode gelap/terang. --}}
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#f8fafc">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#07080F">
<meta name="color-scheme" content="light dark">

{{-- iOS: mode standalone + sembunyikan address bar Safari --}}
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="{{ config('app.short_name', 'Johen Apps') }}">

{{--
    apple-touch-startup-image - iOS hanya, satu per resolusi.
    Logo berada di 42% tinggi layar, jauh dari notch/dynamic island, dan tetap
    di dalam area yang tidak tertutup gesture bar di bawah.
--}}
<link rel="apple-touch-startup-image" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-640x1136.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-750x1334.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-828x1792.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1125x2436.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1170x2532.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1179x2556.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1242x2688.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1284x2778.png') }}">
<link rel="apple-touch-startup-image" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" href="{{ asset('pwa/splash/splash-1290x2796.png') }}">

{{--
    Putuskan apakah overlay splash perlu dirender, SEBELUM body digambar.
    Kalau putuskan di body, akan ada kedipan splash di kunjungan berikutnya.

    Aturan:
      ?splash=0  paksa mati          ?splash=1  paksa tampil
      selain itu  tampil sekali per sesi browser (sessionStorage)

    Kenapa sekali per sesi: aplikasi ini dipakai intensif seharian. Splash
    1,5 detik di setiap page load akan sangat mengganggu.
--}}
<script>
    (function () {
        'use strict';
        try {
            var KEY = 'johen_splash_seen';
            var param = new URLSearchParams(window.location.search).get('splash');
            var show = param === '0' ? false : (param === '1' ? true : sessionStorage.getItem(KEY) !== '1');
            document.documentElement.setAttribute('data-splash', show ? 'on' : 'off');
        } catch (e) {
            document.documentElement.setAttribute('data-splash', 'on');
        }
    })();
</script>

<style>
    /* ---- Overlay splash ----
       Sepenuhnya inline, tidak bergantung Tailwind/Vite, supaya tetap tampil
       walau bundel CSS masih diunduh. */
    #johen-splash {
        position: fixed;
        inset: 0;
        z-index: 9999;
        display: grid;
        place-items: center;
        opacity: 0;
        visibility: hidden;
        pointer-events: none;
        transition: opacity 0.45s ease, visibility 0.45s ease;
        background:
            radial-gradient(120% 60% at 50% 34%, rgba(9, 135, 245, 0.50) 0%, transparent 70%),
            radial-gradient(110% 55% at 42% 78%, rgba(133, 78, 234, 0.34) 0%, transparent 70%),
            #07080F;
    }

    html[data-splash="on"] #johen-splash {
        opacity: 1;
        visibility: visible;
        pointer-events: auto;
    }

    /* Body tidak boleh bisa di-scroll selama splash tampil. */
    html[data-splash="on"] body { overflow: hidden; }

    .johen-splash-stage {
        position: relative;
        display: grid;
        place-items: center;
        width: 190px;
        height: 190px;
    }

    /* Glow di belakang logo, meniru radial-gradient di sidebar. */
    .johen-splash-glow {
        position: absolute;
        inset: -18%;
        border-radius: 24px;
        background: radial-gradient(circle, rgba(9, 135, 245, 0.55), rgba(124, 58, 237, 0.28) 45%, transparent 70%);
        filter: blur(14px);
        animation: johen-splash-glow 2.4s ease-in-out infinite;
    }

    @keyframes johen-splash-glow {
        0%, 100% { opacity: 0.55; transform: scale(0.92); }
        50%      { opacity: 1;    transform: scale(1.08); }
    }

    /* Logo: putar penuh 360deg, restart - sama seperti flipAngle di sidebar
       yang naik ke 360 lalu kembali ke 0. */
    .johen-splash-logo {
        position: relative;
        width: 100%;
        height: 100%;
        object-fit: contain;
        transform-style: preserve-3d;
        animation: johen-splash-flip 1.5s cubic-bezier(0.4, 0, 0.2, 1) infinite;
    }

    @keyframes johen-splash-flip {
        0%   { transform: perspective(900px) rotateY(0deg); }
        100% { transform: perspective(900px) rotateY(360deg); }
    }

    /* Kilau melintas, seperti sweepX di sidebar. */
    .johen-splash-sweep {
        position: absolute;
        inset: 0;
        overflow: hidden;
        border-radius: 20px;
        pointer-events: none;
    }

    .johen-splash-sweep::after {
        content: "";
        position: absolute;
        top: 0;
        bottom: 0;
        width: 45%;
        background: linear-gradient(
            to right,
            transparent,
            rgba(255, 255, 255, 0.22),
            transparent
        );
        transform: translateX(-220%);
        animation: johen-splash-sweep 2.6s cubic-bezier(0.4, 0, 0.2, 1) infinite;
    }

    @keyframes johen-splash-sweep {
        0%        { transform: translateX(-220%); }
        55%, 100% { transform: translateX(320%); }
    }

    .johen-splash-text {
        position: absolute;
        top: calc(100% + 30px);
        left: 50%;
        transform: translateX(-50%);
        text-align: center;
        white-space: nowrap;
    }

    .johen-splash-title {
        font-family: "Plus Jakarta Sans", Inter, system-ui, sans-serif;
        font-size: 1.0625rem;
        font-weight: 800;
        letter-spacing: 0.22em;
        color: #e2e8f0;
        text-indent: 0.22em;
    }

    .johen-splash-sub {
        margin-top: 5px;
        font-size: 0.6875rem;
        font-weight: 500;
        letter-spacing: 0.1em;
        color: #64748b;
    }

    .johen-splash-bar {
        position: fixed;
        left: 50%;
        bottom: calc(38px + env(safe-area-inset-bottom));
        transform: translateX(-50%);
        width: 116px;
        height: 2px;
        border-radius: 999px;
        background: rgba(148, 163, 184, 0.16);
        overflow: hidden;
    }

    .johen-splash-bar::after {
        content: "";
        display: block;
        width: 40%;
        height: 100%;
        border-radius: 999px;
        background: linear-gradient(to right, #0987F5, #854DEA);
        animation: johen-splash-bar 1.15s cubic-bezier(0.4, 0, 0.2, 1) infinite;
    }

    @keyframes johen-splash-bar {
        0%   { transform: translateX(-110%); }
        100% { transform: translateX(360%); }
    }

    @media (prefers-reduced-motion: reduce) {
        .johen-splash-glow,
        .johen-splash-logo,
        .johen-splash-sweep::after,
        .johen-splash-bar::after {
            animation: none !important;
        }
        .johen-splash-bar::after { width: 100%; transform: none; }
    }
</style>

